version: '3.8'

services:

  web:
    container_name: web
    build: .
    working_dir: /src
    command: ["/bin/bash", "/scripts/start.sh"]
    ports:
      - 8000:8000
    volumes:
      - ./src:/src
    env_file:
      - ./.env
    depends_on:
      - postgres-fastapi

  postgres-fastapi:
    container_name: postgres-fastapi
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - ./.env
